### PR TITLE
Move CLI to Typer and improve test coverage to 100%

### LINKED ISSUE #7: Improve/fix help
There seems to be a problem with the help text :smile:   
Would be nice to get actual descriptions instead of variables types :stuck_out_tongue: 

```console
$ poetry run cruft link --help
usage: cruft [-h] [-p PROJECT_DIR] [-u] [-n] [-c CONFIG_FILE] [-d]
             [-e EXTRA_CONTEXT]
             template_git_url

Links an existing project created from a template, to the template it was
created from. Examples: link( 'https://github.com/timothycrosley/cookiecutter-
python/', no_input=True, use_latest=True ) -------

positional arguments:
  template_git_url      String

optional arguments:
  -h, --help            show this help message and exit
  -p PROJECT_DIR, --project_dir PROJECT_DIR
                        String
  -u, --use_latest      Boolean
  -n, --no_input        Boolean
  -c CONFIG_FILE, --config_file CONFIG_FILE
                        Union type; Union[X, Y] means either X or Y. To define
                        a union, use e.g. Union[int, str]. Details: - The
                        arguments must be types and there must be at least
                        one. - None as an argument is a special case and is
                        replaced by type(None). - Unions of unions are
                        flattened, e.g.:: Union[Union[int, str], float] ==
                        Union[int, str, float] - Unions of a single argument
                        vanish, e.g.:: Union[int] == int # The constructor
                        actually returns int - Redundant arguments are
                        skipped, e.g.:: Union[int, str, int] == Union[int,
                        str] - When comparing unions, the argument order is
                        ignored, e.g.:: Union[int, str] == Union[str, int] -
                        When two arguments have a subclass relationship, the
                        least derived argument is kept, e.g.:: class Employee:
                        pass class Manager(Employee): pass Union[int,
                        Employee, Manager] == Union[int, Employee]
                        Union[Manager, int, Employee] == Union[int, Employee]
                        Union[Employee, Manager] == Employee - Similar for
                        object:: Union[int, object] == object - You cannot
                        subclass or instantiate a union. - You can use
                        Optional[X] as a shorthand for Union[X, None].
  -d, --default_config  Boolean
  -e EXTRA_CONTEXT, --extra_context EXTRA_CONTEXT
                        Union type; Union[X, Y] means either X or Y. To define
                        a union, use e.g. Union[int, str]. Details: - The
                        arguments must be types and there must be at least
                        one. - None as an argument is a special case and is
                        replaced by type(None). - Unions of unions are
                        flattened, e.g.:: Union[Union[int, str], float] ==
                        Union[int, str, float] - Unions of a single argument
                        vanish, e.g.:: Union[int] == int # The constructor
                        actually returns int - Redundant arguments are
                        skipped, e.g.:: Union[int, str, int] == Union[int,
                        str] - When comparing unions, the argument order is
                        ignored, e.g.:: Union[int, str] == Union[str, int] -
                        When two arguments have a subclass relationship, the
                        least derived argument is kept, e.g.:: class Employee:
                        pass class Manager(Employee): pass Union[int,
                        Employee, Manager] == Union[int, Employee]
                        Union[Manager, int, Employee] == Union[int, Employee]
                        Union[Employee, Manager] == Employee - Similar for
                        object:: Union[int, object] == object - You cannot
                        subclass or instantiate a union. - You can use
                        Optional[X] as a shorthand for Union[X, None].
```

### LINKED ISSUE #23: Relative paths are not supported
`cruft check` can fail if the project has been created with a relative path.

Cruft version: 1.1.2.

**Works** as expected:
- `cruft create --no_input $PWD/cookiecutter-custom-template`
- `cruft create --no_input file://$PWD/cookiecutter-custom-template`

**Fails** when running `cruft check`:
- `cruft create --no_input cookiecutter-custom-template`

### LINKED ISSUE #31: Move the CLI from hug to click
Disclaimer - this is just a suggestion. Feel free to close it. click is IMHO may be a better suited framework for creating CLIs than hug. I think where hug really shines is for creating web APIs but for clis I think click has a competitive edge since it was designed with just CLI applications in mind. Click supports better documentation, input types and has click.testing for testing support. It also handles type annotations better than hug. I know hug is maintained by @timothycrosley and since cruft is your project you may want to use it. 

Other benefits are that cookiecutter itself use click. This way we can avoid adding another dependency for our downstream users and possibly reuse more of cookiecutter internals, making the cruft wrapping logic even thinner. This will allow for better compatibility with cookiecutter.

### LINKED ISSUE #39: Drop support for windows? (Cruft will still be available with WSL)
`cruft update` currently doesn't work with windows. Given that is the main selling point of `cruft` I think we should drop windows support. I have a couple of reasons for doing so -

- Cookiecutter and cruft are dev tools
- Windows doesn't really come with a git executable by default it doesn't make sense to have windows support.
- For windows users who program - they can use WSL anyway.
- I don't have a Windows laptop to test/develop windows code. I am guessing @timothycrosley doesn't have one either

This will reduce a lot of code in the repo and allow us to focus on environments which are used by devs.

### PR DESCRIPTION
**Pull request by samj1912**
This PR moves the CLI to typer with which we now have proper CLI help and also a slight update in terms of CLI options.
It also improves test coverage to a 100% once all the actions in all the OS run (codecov allows you to combine coverage reports from different environments! That is neat!). Apart from that this PR also makes user dependency on `examples` optional.

Fixes #31 
Fixes #7
Fixes #23 
Resolves #39 

Breaking changes with 1.x to note - 

- The cruft api has now moved from `cruft.api` to `cruft`. 
- Calling cruft via the API defaults to non-interactive flags of the command where as with the CLI version, interactive flags are used. 
- Drops support for Windows directly. See #39 for rationale and more details. `cruft update` is already broken for Windows pr #16 Moving forward Windows users are encouraged to use `cruft` via `WSL`
- `use_latest` in `link` has been removed and replaced with `checkout` which accepts branches, tags and commits and `link` always uses the latest commit of the provided reference. This is much more useful than users providing SHA hashes, as they can now link against release tags for eg while still maintaining compatibility to link against a particular commit.
- `cookiecutter_input` flag in `update` now only asks from inputs for the new version of the template and uses `.cruft.json` context for the currently linked version. This is to ensure that users don't modify the context with which the template was linked during an `update`
- Not a breaking change but a change in behaviour - if directory is not provided by user, it is now serialized as a null instead of a blank string in cruft.json

Other improvements - 
Add caching for poetry to CI. This significantly reduces the time taken for CI from ~5 mins to 1min.
Add pytest-xdist to run multiple tests at a time. Given that most of the tests are I/O bound this leads to significant speed ups.

### CODE REVIEW

**Comment by timothycrosley** [comment]
This is looking great! Some initial thoughts:

- It's probably worth keeping the programmatic API and the CLI interface separate if using typer / click. Trying out some examples locally, it seems that typer options have weird behaviour if you try calling the function directly.
- Along the same lines, I think the programmatic API should be kept as easily accessible as possible. I think we have the oppurtunity to improve it here by moving it to the root:

```import cruft

help(cruft)
cruft.create(...
```
- One nice thing about the examples, beyond there secondary support as tests, is they end up in the autogenerated documentation: https://timothycrosley.github.io/cruft/reference/cruft/api/#create. I assume that the reason they needed to be removed was direct translation to typer, but I think if we have typer functions that call the Python API then the Python API can keep them in place.

**Comment by samj1912** [comment]
I have added back the api and moved it all to `cruft` to make it simple. I have also hidden all the other modules from docs as private modules since users should not be concerned about those expect the api exposed in `cruft`

The last part that is left is adding the CLI tests which I will be doing now. I will also try to aim for 100% coverage.

**Comment by samj1912** [comment]
Depending on the resolution of #37, I might remove the windows specific hacks.

**Comment by samj1912** [comment]
@timothycrosley done! Can you please draft a new release? 

On a S/N - Thank you for being so responsive to these PRs and changes!

**Comment by timothycrosley** [comment]
2.0.0 has been deployed :tada:! Great work! 

I'm happy to do what I can, I'm just really happy to see the project move forward :)

**Pull request merged**
