### PR TITLE
cruft update cruft to latest timothycrosley/cookiecutter-python

### PR DESCRIPTION
**Pull request by Peter200lx**
While playing with cruft trying to build git history integration I realized that cruft was out of date with its own template.

### CODE REVIEW

**Comment by Peter200lx** [comment]
Ahh, was digging into that failure. The dependency came from the updated cookiecutter-python.

**Comment by Peter200lx** [comment]
Hmm, with the new failure should we update numpy here in cruft, or update the template and then re `cruft update` this project?

**Comment by Peter200lx** [comment]
I'm not finding any way that `numpy` is even referenced via any dependency chain. Maybe the travis-ci worker didn't get cleaned and has the library already installed? Is strange it failed for the 3.7 run but not the 3.6 run (I use 3.7 on my local box without issue)

**Comment by timothycrosley** [comment]
I agree, this seems like a travis-ci bug on 3.7. Unfortunate, but I'll work around it for now.

**Pull request merged**
